### ISSUE TITLE
Image hotpot questions

### ISSUE THREAD

**Issue by danfathom** [born05/craft-imagehotspots#20]
Just wondering with your plugin, how does the backend interface work with adding hotspots- is it a drag and drop system - or do you need to enter hotspot x and y axis?

also with the field - can the hotspots open a popup where you can pull through information from and entry?

We would also need to be able to change the colour of the hotspot dots based on fields from the entry.

**Comment by roelvanhintum** [comment]
Hi @danfathom, the interface is a modal where you can drag and visually see where the hotspot is going to be. There is currently no additional info in the hotspot modal/popup, because we don't handle any other data. On the admin side things are limited, because the plugin only handles hotspots in relation to the input image. The data/front-end part is completely up to you, the plugin just returns a field containing x and y coordinates next to all other fields in an entry.
